REPO = $(HOME)/AssignmentEx07/sources
INCLUDES= -I $(HOME)/AssignmentEx07/headers

$(HOME)/AssignmentEx07/excu: main.cpp $(REPO)/mark.cpp $(REPO)/mariam.cpp
	g++ $(INCLUDES) main.cpp $(REPO)/mark.cpp $(REPO)/mariam.cpp -o $(HOME)/AssignmentEx07/excu